name: elite_kit
description: A convenient extension of Flutter.
version: 0.0.1
author: Insofan
email: insofan3156@gmail.com
homepage: https://github.com/Insofan/elite_kit

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

